name: 'molekoola, consult culture '
favicon: null
layout_spectrum: 1
typography_spectrum: 0.756
title: 'Molekoola, Branding, Marketing, Communication Consult Culture '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5b5b5d'
    - '#ffffff'
    - '#86858b'
    - '#000106'
    - '#facc74'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
