name: molekoola
favicon: null
layout_spectrum: 1
typography_spectrum: 0.756
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5b5b5d'
    - '#ffffff'
    - '#86858b'
    - '#000106'
    - '#facc74'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
